---

- name:  Install packages
  delegate_to: labproxy
  become: true
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - nginx
    - certbot

- name: Allow Nginx to reverse proxy
  delegate_to: labproxy
  become: true
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  notify:
    - restart nginx

- name: NGINX | Starting NGINX
  delegate_to: labproxy
  become: true
  service:
    name: nginx
    state: started
    enabled: yes

- name: Run certbot to create ssl certs
  delegate_to: labproxy
  become: true
  shell: |
    certbot certonly \
    --webroot -w /usr/share/nginx/html \
    -d {{ lab_domain }} \
    --email rcoward@ukcloud.com \
    --text --agree-tos --renew-by-default
  args:
    creates: /etc/letsencrypt/live/{{ lab_domain }}/fullchain.pem
  notify:
    - restart nginx

- name: Setup HTTPS redirect
  delegate_to: labproxy
  become: true
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html

- name: Configure SSL for Nginx
  delegate_to: labproxy
  become: true
  template:
    src: nginx-site.conf.j2
    dest: /etc/nginx/conf.d/guacamole.conf
  notify:
    - restart nginx

- name: Remove default nginx configured
  delegate_to: labproxy
  become: true
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify:
    - restart nginx

- name: Add cron job for 'certbot renew' (if configured).
  delegate_to: labproxy
  become: true
  cron:
    name: Certbot automatic renewal.
    job: "certbot renew --quiet --no-self-upgrade"
    minute: "{{ certbot_auto_renew_minute }}"
    hour: "{{ certbot_auto_renew_hour }}"
    user: "root"
    cron_file: certbot

